fake_data:
  folder_path: ./data/players
  num_files: 5

datalake:
  endpoDOUBLE: localhost:9000
  bucket_name: data-big-5-leagues
  folder_name: players
  access_key: minio_access_key
  secret_key: minio_secret_key